import type { ReactNode } from 'react';
import ActionPanel from '../components/ActionPanel';
import Badge from '../components/Badge';
import Card from '../components/Card';
import DataTable from '../components/DataTable';
import EvidenceChecklist from '../components/EvidenceChecklist';
import LifecycleStepper from '../components/LifecycleStepper';
import MetricCard from '../components/MetricCard';
import StatusBadge from '../components/StatusBadge';
import StatePill from '../components/StatePill';
import { auditEvents, cm2Records, milestones, opportunities, pabMeetings, podCapacity, projects, rbacRows } from '../data/mockData';

const Tabs = ({ items }: { items: string[] }) => <div className='mb-3 flex flex-wrap gap-2'>{items.map((t, i) => <span key={t} className={`rounded px-3 py-1 text-xs ${i === 0 ? 'bg-slate-900 text-white' : 'bg-slate-100 text-slate-700'}`}>{t}</span>)}</div>;

export const screenNames = ['Executive Home','O2O Pipeline','Opportunity Detail','PAB Governance','Financial Approval Queue','RFP & Bid Management','MOU Workspace','O2C Projects','O2C Project Detail','Milestone-to-Cash Tracker','Finance & CM2 Dashboard','Pod Capacity Dashboard','Audit Log','Admin / RBAC'] as const;

export const screens: Record<string, ReactNode> = {
  'Executive Home': <div className='space-y-3'><div className='grid gap-3 md:grid-cols-4'><MetricCard label='Active Opportunities' value={opportunities.length} /><MetricCard label='Open Blockers' value={opportunities.flatMap((o) => o.blockers).length} /><MetricCard label='Live O2C Projects' value={projects.length} /><MetricCard label='Realization' value='64%' /></div><Card title='Governance Guardrails'><EvidenceChecklist items={[{ label: 'Orders Won derived from evidence records (not Kanban columns)', ok: true }, { label: 'Soft deleted records retained in audit', ok: true }, { label: 'Revenue Capture Pod accountable until 100% collection', ok: true }]} /></Card></div>,
  'O2O Pipeline': <Card title='Opportunity Governance Pipeline'><DataTable cols={['Opportunity', 'Stage', 'State', 'Owner', 'Value (Cr)', 'Status']} rows={opportunities.map((o) => [o.name, <StatusBadge status={o.stage} />, o.state, o.owner, o.valueCr, <StatePill state={o.status} />])} /></Card>,
  'Opportunity Detail': <div className='grid gap-3 lg:grid-cols-3'><section className='space-y-3 lg:col-span-2'><Card title='Opportunity: UP School Digital Labs'><Tabs items={['Overview','Proposal','PABs','Financials / CM2','RFP & Bid','MOU','Documents','Activity / Audit']} /><LifecycleStepper steps={['Sourcing', 'Pre-Bid PAB', 'Bid', 'Negotiation', 'Won']} current={2} /><div className='mt-3'><DataTable cols={['Module', 'State', 'Notes']} rows={[[ 'Proposal', 'approved', 'Tech + commercial signed by Sales Director' ],[ 'PABs', 'loading', 'Pre-bid decision queueing board review' ],[ 'RFP & Bid', 'blocked', 'CFO sign-off not complete' ],[ 'MOU', 'empty', 'Not initiated' ],[ 'Documents', 'delayed', 'Award communication pending' ],[ 'Activity / Audit', 'approved', 'All actions logged incl. soft-deletes' ]]} /></div></Card></section><ActionPanel requiredAction='Complete CFO sign-off for BD-77' owner='CFO - Finance Office' blocker='Bid submission hard-blocked by governance rule' artifact='CFO sign-off memo + digital approval stamp' sla='2 days overdue (Aging: 5 days)' nextAction='Submit bid package to RFP portal' /></div>,
  'PAB Governance': <Card title='PAB Decisions'><DataTable cols={['ID', 'Type', 'Decision', 'Context', 'Trigger', 'State']} rows={pabMeetings.map((p) => [p.id, p.type, <Badge text={p.decision} />, p.context, p.trigger || '—', <StatePill state={p.status} />])} /></Card>,
  'Financial Approval Queue': <Card title='Approvals'><DataTable cols={['Item', 'Rule Check', 'Status']} rows={[['BD-77', 'CFO sign-off required before submission', <StatePill state='blocked' />], ['INV-33', 'Margin erosion >5% requires mid-project PAB', <StatePill state='rejected' />], ['MS-2 invoice', 'Proof upload mismatch', <StatePill state='delayed' />]]} /></Card>,
  'RFP & Bid Management': <Card title='RFP and Bid Governance'><DataTable cols={['Bid', 'Linked Opp', 'CFO Sign-off', 'Award Evidence', 'Submission']} rows={[['BD-77', 'UP School Digital Labs', 'Missing', 'N/A', 'Blocked'], ['BD-72', 'Bihar FLN Expansion', 'Completed', 'Uploaded', 'Submitted']]} /></Card>,
  'MOU Workspace': <Card title='MOU Upload Registry'><DataTable cols={['Opportunity', 'Signed MOU', 'O2C Transition']} rows={opportunities.map((o) => [o.name, o.signedMou ? 'Uploaded' : 'Missing', o.signedMou ? 'Allowed' : 'Blocked'])} /></Card>,
  'O2C Projects': <Card title='Project Portfolio'><DataTable cols={['Project', 'Pod Owner', 'Collection%', 'Status', 'Lifecycle']} rows={projects.map((p) => [p.name, p.podOwner, p.collectionPct, p.status, <StatePill state={p.lifecycleState} />])} /></Card>,
  'O2C Project Detail': <div className='grid gap-3 lg:grid-cols-3'><section className='space-y-3 lg:col-span-2'><Card title='Project: Bihar FLN Expansion'><Tabs items={['Overview','Milestones','Proofs','Invoices','Collections','Scope Changes','CM2','PABs','Audit']} /><DataTable cols={['Track', 'State', 'Detail']} rows={[[ 'Milestones', 'approved', '2/3 milestones complete' ],[ 'Proofs', 'loading', 'District onboarding proof in review' ],[ 'Invoices', 'blocked', 'Invoice trigger waits for proof verification' ],[ 'Collections', 'delayed', '64% collected; pod remains accountable' ],[ 'Scope Changes', 'rejected', 'Change request denied by PAB' ],[ 'CM2', 'approved', 'CM2 at 23%' ],[ 'PABs', 'approved', 'Mid-project PAB executed for risk' ],[ 'Audit', 'terminal', 'Immutable record archived for closed items' ]]} /></Card></section><ActionPanel requiredAction='Upload delivery proof for MS-2' owner='Program Manager + Delivery Lead' blocker='Invoice cannot be triggered without validated proof' artifact='Geo-tagged deployment proof + signoff sheet' sla='Due in 1 day (Aging: 0)' nextAction='Trigger invoice and notify Revenue Capture Pod' /></div>,
  'Milestone-to-Cash Tracker': <Card title='Milestone Cashflow'><DataTable cols={['Milestone', 'Amount (L)', 'Delivery', 'Invoice', 'Collection', 'State']} rows={milestones.map((m) => [m.name, m.amountL, m.delivered ? 'Done' : 'Pending', m.invoiced ? 'Done' : 'Pending', m.collected ? 'Done' : 'Pending', <StatePill state={m.state} />])} /></Card>,
  'Finance & CM2 Dashboard': <Card title='CM2 Oversight'><DataTable cols={['Project ID', 'Budget L', 'Actual L', 'CM2%']} rows={cm2Records.map((c) => [c.projectId, c.budgetL, c.actualL, c.cm2Pct])} /></Card>,
  'Pod Capacity Dashboard': <Card title='Pod Capacity and Load'><DataTable cols={['Pod', 'Used', 'Total', 'Utilization']} rows={podCapacity.map((p) => [p.pod, p.used, p.total, `${Math.round((p.used / p.total) * 100)}%`])} /></Card>,
  'Audit Log': <Card title='Audit Trail'><DataTable cols={['Time', 'Entity', 'Action', 'Actor']} rows={auditEvents.map((a) => [a.ts, a.entity, `${a.action}${a.softDeleted ? ' (soft-delete retained)' : ''}`, a.actor])} /></Card>,
  'Admin / RBAC': <div className='space-y-3'><Card title='Role and Action-level Permissions'><DataTable cols={['Role', 'Action-level Permissions']} rows={rbacRows.map((r) => [r.role, r.permissions.join(' | ')])} /></Card><Card title='Policy States'><DataTable cols={['State', 'Meaning']} rows={[[ <StatePill state='empty' />, 'No record or artifact yet' ],[ <StatePill state='loading' />, 'Pending review/processing' ],[ <StatePill state='blocked' />, 'Hard rule prevents progression' ],[ <StatePill state='approved' />, 'Passed governance check' ],[ <StatePill state='rejected' />, 'Explicitly denied by authority' ],[ <StatePill state='delayed' />, 'Missed SLA or aging risk' ],[ <StatePill state='terminal' />, 'Final closed immutable state' ]]} /></Card></div>,
};
