import { opportunities,projects,pabMeetings,milestones,cm2,podCapacity,audit,rbac } from '../data/mockData';
import { Card,MetricCard,DataTable,LifecycleStepper,EvidenceChecklist,ActionPanel,StatusBadge,Badge,Drawer,Modal } from '../components/ui';

export const screens:Record<string,JSX.Element>={
'Executive Home':<div className='grid md:grid-cols-4 gap-3'><MetricCard label='Active Opportunities' value={opportunities.length}/><MetricCard label='O2C Projects' value={projects.length}/><MetricCard label='Open Blockers' value={3}/><MetricCard label='Collection Realization' value='64%'/><Card title='Governance Guardrails'><EvidenceChecklist items={[{label:'Orders Won = evidence-backed only (not Kanban)',ok:true},{label:'Soft deleted records retained in audit',ok:true},{label:'Revenue Capture Pod accountable till 100% collection',ok:true}]}/></Card></div>,
'O2O Pipeline':<Card title='Pipeline by Stage'><DataTable cols={['Opportunity','Stage','Owner','Value (Cr)','Blockers']} rows={opportunities.map(o=>[o.name,<StatusBadge status={o.stage}/>,o.owner,o.valueCr,o.blockers.join(', ')||'—'])}/></Card>,
'Opportunity Detail':<div className='space-y-3'><Card title='UP School Digital Labs'><LifecycleStepper steps={['Sourcing','Pre-Bid PAB','Bid','Negotiation','Won']} current={2}/><EvidenceChecklist items={[{label:'CFO sign-off completed',ok:false},{label:'Award communication uploaded',ok:false},{label:'Signed MOU uploaded',ok:false}]}/></Card><ActionPanel>CFO sign-off is a hard blocker before bid submission.</ActionPanel></div>,
'PAB Governance':<Card title='PAB Board'><DataTable cols={['ID','Type','Context','Decision','Trigger']} rows={pabMeetings.map(p=>[p.id,p.type,p.context,<Badge text={p.decision}/>,p.trigger||'—'])}/></Card>,
'Financial Approval Queue':<Card title='Pending Finance Actions'><DataTable cols={['Item','Rule','Status']} rows={[[ 'Bid BD-77','CFO sign-off blocks bid submission','Pending CFO'],['Invoice INV-33','Margin erosion >5% requires review','Escalated']]}/></Card>,
'RFP & Bid Management':<Card title='Bids'><DataTable cols={['Bid','Linked Opp','CFO','Submission']} rows={[[ 'BD-77','UP School Digital Labs','Not Signed','Blocked'],['BD-72','Bihar FLN Expansion','Signed','Submitted']]}/></Card>,
'MOU Workspace':<Drawer title='MOU Records'><DataTable cols={['Opportunity','Signed MOU','O2C Start']} rows={opportunities.map(o=>[o.name,o.signedMou?'Uploaded':'Missing',o.signedMou?'Allowed':'Blocked'])}/></Drawer>,
'O2C Projects':<Card title='Project Registry'><DataTable cols={['Project','Pod','Collection%','Risk']} rows={projects.map(p=>[p.name,p.pod,p.collectionPct,p.risk])}/></Card>,
'O2C Project Detail':<div className='space-y-3'><Card title='Bihar FLN Expansion'><EvidenceChecklist items={[{label:'MOU signed prior to O2C',ok:true},{label:'Revenue pod accountable till full collection',ok:false}]}/></Card><Modal title='Mid-Project PAB Trigger'>Trigger due to timeline risk + margin erosion.</Modal></div>,
'Milestone-to-Cash Tracker':<Card title='Milestone to Cash'><DataTable cols={['Milestone','Amount (L)','Delivered','Invoiced','Collected']} rows={milestones.map(m=>[m.name,m.amountL,m.delivered?'Yes':'No',m.invoiced?'Yes':'No',m.collected?'Yes':'No'])}/></Card>,
'Finance & CM2 Dashboard':<Card title='CM2 Performance'><DataTable cols={['Project','CM2%','Budget L','Actual L']} rows={cm2.map(c=>[c.projectId,c.cm2Pct,c.budgetL,c.actualL])}/></Card>,
'Pod Capacity Dashboard':<Card title='Pod Capacity'><DataTable cols={['Pod','Used','Total','Utilization']} rows={podCapacity.map(p=>[p.pod,p.used,p.total,`${Math.round(p.used/p.total*100)}%`])}/></Card>,
'Audit Log':<Card title='Audit Timeline'><DataTable cols={['When','Entity','Action','Actor']} rows={audit.map(a=>[a.ts,a.entity,`${a.action}${a.softDeleted?' (retained soft-delete)': ''}`,a.actor])}/></Card>,
'Admin / RBAC':<Card title='Role Permissions'><DataTable cols={['Role','Permissions']} rows={rbac.map(r=>[r.role,r.permissions.join(', ')])}/></Card>
};
