import { useMemo, useState, type ReactNode } from 'react';

type TopTab = 'Home' | 'Admin' | 'Audit Log';
type Role =
  | 'Admin' | 'BD' | 'GI' | 'RC Pod' | 'Business Lead' | 'GI Lead' | 'Pod Sponsor'
  | 'Delivery-track Sponsor' | 'Platform-track Sponsor' | 'Rishabh / CXO Lead' | 'Prateek / CXO Lead'
  | 'CFO / Somesh' | 'Finance Ops' | 'CCOO / Viprav' | 'Tender Team' | 'Delivery Pod Lead'
  | 'Delivery Pod User' | 'Program Pod User' | 'Mission M&E' | 'Founders Office' | 'Portfolio Intelligence' | 'Readonly';
type Stage = 'Opportunity Registration' | 'Proposal Stage' | 'Pre-Bid PAB' | 'Financial Approval Gate' | 'RFP & Bid Management' | 'Post-Bid PAB' | 'MOU Stage' | 'O2C Transition Ready';
type Status = 'Active' | 'Lost' | 'No-Bid' | 'Dropped' | 'Archived' | 'On Hold' | 'No-Go';
type CStatus = 'Not completed' | 'Completed' | 'Not required';

type ChecklistItem = { id: string; title: string; status: CStatus; note: string; evidenceRequired?: boolean; sourceRule?: string; gating: boolean; files: number };
type Comment = { id: string; author: string; at: string; text: string };
type FileRow = { id: string; name: string; type: string; checklist: string; by: string; date: string };
type Opportunity = {
  id: string; name: string; department: string; customer: string; type: 'B2G' | 'B2B'; motion: 'Farming' | 'Hunting';
  products: string[]; geos: string[]; valueCr: number; expectedClose: string; owner: string; giOwner: string; rcPod: string; podSponsor: string;
  stage: Stage; status: Status; probability: number; daysInStage: number; currentBlocker: string; nextAction: string;
  checklists: Record<Stage, ChecklistItem[]>; comments: Comment[]; files: FileRow[];
  cfoSigned: boolean; bidSubmitted: boolean; awardUploaded: boolean; mouUploaded: boolean; pabDecision?: 'Go'|'Conditional Go'|'Hold'|'No-Go';
};
type Audit = { id: string; time: string; user: string; event: string; opportunity: string; details: string };

const stages: Stage[] = ['Opportunity Registration','Proposal Stage','Pre-Bid PAB','Financial Approval Gate','RFP & Bid Management','Post-Bid PAB','MOU Stage','O2C Transition Ready'];
const probs: Record<Stage, number> = {'Opportunity Registration':10,'Proposal Stage':25,'Pre-Bid PAB':35,'Financial Approval Gate':45,'RFP & Bid Management':60,'Post-Bid PAB':75,'MOU Stage':90,'O2C Transition Ready':100};
const roles: Role[] = ['Admin','BD','GI','RC Pod','Business Lead','GI Lead','Pod Sponsor','Delivery-track Sponsor','Platform-track Sponsor','Rishabh / CXO Lead','Prateek / CXO Lead','CFO / Somesh','Finance Ops','CCOO / Viprav','Tender Team','Delivery Pod Lead','Delivery Pod User','Program Pod User','Mission M&E','Founders Office','Portfolio Intelligence','Readonly'];
const now = () => new Date().toISOString().replace('T',' ').slice(0,16);

const templates: Record<Stage, string[]> = {
  'Opportunity Registration': ['Customer signal captured','Budget signal captured','Stakeholder mapping completed','Competitor intelligence captured'],
  'Proposal Stage': ['Problem framing completed','Scope and timelines documented','CM2 pricing sheet prepared','Rollout assumptions documented','Success definition articulated','Platform dependencies identified','Risk assumptions uploaded','Stakeholder map uploaded'],
  'Pre-Bid PAB': ['Proposal submitted to CXO layer','Pre-Bid PAB scheduled','Platform feasibility validated','Delivery feasibility validated','Capacity read captured','CM2 aligned with CCOO-approved pricing strategy','PAB decision recorded'],
  'Financial Approval Gate': ['Margin validation completed','Commercial risk reviewed','Payment milestones reviewed','CM2 approved','Third-party delivery expenses approved','CFO sign-off recorded'],
  'RFP & Bid Management': ['RFP document uploaded','Technical bid uploaded','Financial bid uploaded','EMD / tender fee proof uploaded','Compliance checklist completed','Submission acknowledgement stored','Award communication uploaded, if won'],
  'Post-Bid PAB': ['Capacity readiness reviewed','Execution plan completed','Pod creation recommendation recorded','Hiring requests recorded','Risk register created','O2C readiness confirmed'],
  'MOU Stage': ['MOU draft uploaded','Scope alignment confirmed','Pricing alignment confirmed','Payment milestone clarity confirmed','Operational realism confirmed','Prateek sign-off recorded','Rishabh sign-off recorded','Signed MOU uploaded'],
  'O2C Transition Ready': ['Transition packet confirmed']
};
const mkChecklist = (): Record<Stage, ChecklistItem[]> => Object.fromEntries(stages.map((s)=>[s,templates[s].map((t,i)=>({id:`${s}-${i}`,title:t,status:i<2?'Completed':'Not completed',note:'',evidenceRequired:i%2===0,sourceRule:i%3===0?'PRD Rule':undefined,gating:true,files:0}))])) as Record<Stage, ChecklistItem[]>;

const seed: Opportunity[] = [
  {id:'OP-401',name:'UP Foundational Learning Renewal',department:'Education Dept',customer:'UP DoE',type:'B2G',motion:'Hunting',products:['LMS','Assessment'],geos:['UP'],valueCr:32,expectedClose:'2026-07-30',owner:'Aditi (BD)',giOwner:'Vikram (GI)',rcPod:'RC North',podSponsor:'N. Kapoor',stage:'Opportunity Registration',status:'Active',probability:10,daysInStage:4,currentBlocker:'Budget confirmation pending',nextAction:'Capture budget memo',checklists:mkChecklist(),comments:[],files:[],cfoSigned:false,bidSubmitted:false,awardUploaded:false,mouUploaded:false},
  {id:'OP-355',name:'CSR STEM Enablement',department:'CSR',customer:'Apex Industries',type:'B2B',motion:'Farming',products:['STEM Kits'],geos:['MH'],valueCr:14,expectedClose:'2026-06-25',owner:'Rohan (BD)',giOwner:'Meera (GI)',rcPod:'RC West',podSponsor:'P. Bhat',stage:'Proposal Stage',status:'Active',probability:25,daysInStage:8,currentBlocker:'Risk assumptions doc pending',nextAction:'Upload risk assumptions',checklists:mkChecklist(),comments:[],files:[],cfoSigned:false,bidSubmitted:false,awardUploaded:false,mouUploaded:false},
  {id:'OP-287',name:'State Tablet Upgrade',department:'School IT',customer:'MP Education',type:'B2G',motion:'Hunting',products:['Device Mgmt','LMS'],geos:['MP'],valueCr:48,expectedClose:'2026-08-15',owner:'Ishita (BD)',giOwner:'Neel (GI)',rcPod:'RC Central',podSponsor:'R. Jain',stage:'Pre-Bid PAB',status:'Active',probability:35,daysInStage:3,currentBlocker:'PAB decision pending',nextAction:'Record PAB minutes',checklists:mkChecklist(),comments:[],files:[],cfoSigned:false,bidSubmitted:false,awardUploaded:false,mouUploaded:false},
  {id:'OP-266',name:'District FLN Scale-Up',department:'FLN Mission',customer:'Bihar Dept',type:'B2G',motion:'Farming',products:['Teacher App','Assessment'],geos:['BR'],valueCr:28,expectedClose:'2026-07-12',owner:'Karan (BD)',giOwner:'Sana (GI)',rcPod:'RC East',podSponsor:'M. Das',stage:'Financial Approval Gate',status:'Active',probability:45,daysInStage:6,currentBlocker:'CFO sign-off pending',nextAction:'Get CFO approval',checklists:mkChecklist(),comments:[],files:[],cfoSigned:false,bidSubmitted:false,awardUploaded:false,mouUploaded:false},
  {id:'OP-222',name:'Govt Exam Prep Stack',department:'Skill Mission',customer:'Rajasthan Mission',type:'B2G',motion:'Hunting',products:['Exam Platform'],geos:['RJ'],valueCr:19,expectedClose:'2026-06-18',owner:'Pooja (BD)',giOwner:'Harsh (GI)',rcPod:'RC North',podSponsor:'A. Sen',stage:'RFP & Bid Management',status:'Active',probability:60,daysInStage:9,currentBlocker:'EMD proof upload pending',nextAction:'Upload EMD proof',checklists:mkChecklist(),comments:[],files:[],cfoSigned:true,bidSubmitted:false,awardUploaded:false,mouUploaded:false},
  {id:'OP-204',name:'Smart Lab Continuation',department:'Education',customer:'Odisha DoE',type:'B2G',motion:'Farming',products:['STEM Kits','LMS'],geos:['OD'],valueCr:24,expectedClose:'2026-05-28',owner:'Tanuj (BD)',giOwner:'Anika (GI)',rcPod:'RC East',podSponsor:'R. Dey',stage:'Post-Bid PAB',status:'Active',probability:75,daysInStage:5,currentBlocker:'Risk register missing',nextAction:'Create risk register',checklists:mkChecklist(),comments:[],files:[],cfoSigned:true,bidSubmitted:true,awardUploaded:true,mouUploaded:false},
  {id:'OP-171',name:'Learning Outcomes Partnership',department:'Mission',customer:'Punjab Mission',type:'B2G',motion:'Hunting',products:['Assessment','M&E'],geos:['PB'],valueCr:21,expectedClose:'2026-06-10',owner:'Reva (BD)',giOwner:'Arjun (GI)',rcPod:'RC North',podSponsor:'S. Talwar',stage:'MOU Stage',status:'Active',probability:90,daysInStage:7,currentBlocker:'Signed MOU not uploaded',nextAction:'Upload signed MOU',checklists:mkChecklist(),comments:[],files:[],cfoSigned:true,bidSubmitted:true,awardUploaded:true,mouUploaded:false},
  {id:'OP-099',name:'Digital Classroom Renewal',department:'State Education',customer:'Delhi DoE',type:'B2G',motion:'Farming',products:['LMS'],geos:['DL'],valueCr:16,expectedClose:'2026-05-25',owner:'Nitin (BD)',giOwner:'Priya (GI)',rcPod:'RC Metro',podSponsor:'V. Shah',stage:'O2C Transition Ready',status:'Active',probability:100,daysInStage:2,currentBlocker:'None',nextAction:'Handover to O2C',checklists:mkChecklist(),comments:[],files:[],cfoSigned:true,bidSubmitted:true,awardUploaded:true,mouUploaded:true},
];

export default function App(){
  const [tab,setTab]=useState<TopTab>('Home'); const [role,setRole]=useState<Role>('BD'); const [query,setQuery]=useState(''); const [showArchived,setShowArchived]=useState(false);
  const [opps,setOpps]=useState(seed); const [audit,setAudit]=useState<Audit[]>([]); const [active,setActive]=useState<Opportunity|null>(null); const [dtab,setDtab]=useState('Checklist'); const [showAdd,setShowAdd]=useState(false);
  const [filters,setFilters]=useState({type:'All',product:'All',geo:'All',stage:'All',status:'All',salesperson:'All'});
  const log=(event:string,op:Opportunity|string,details:string)=>setAudit(p=>[{id:`a${Date.now()}`,time:now(),user:role,event,opportunity:typeof op==='string'?op:op.name,details},...p]);
  const can=(perm:'add'|'admin'|'pab'|'cfo'|'tender'|'mou'|'edit')=>({add:['BD'],admin:['Admin'],pab:['Rishabh / CXO Lead','Prateek / CXO Lead'],cfo:['CFO / Somesh'],tender:['Tender Team'],mou:['GI'],edit:roles.filter(r=>r!=='Readonly')}[perm] as Role[]).includes(role);

  const view=opps.filter(o=>(showArchived||o.status!=='Archived')&&`${o.name} ${o.customer}`.toLowerCase().includes(query.toLowerCase())&&(filters.type==='All'||o.type===filters.type)&&(filters.stage==='All'||o.stage===filters.stage)&&(filters.status==='All'||o.status===filters.status)&&(filters.salesperson==='All'||o.owner===filters.salesperson)&&(filters.geo==='All'||o.geos.includes(filters.geo))&&(filters.product==='All'||o.products.includes(filters.product)));
  const kpi=useMemo(()=>({total:view.reduce((a,b)=>a+b.valueCr,0),weighted:view.reduce((a,b)=>a+(b.valueCr*b.probability/100),0),high:view.filter(o=>o.probability>=75).length,won:view.filter(o=>o.stage==='O2C Transition Ready').length}),[view]);
  const pending=(o:Opportunity)=>o.checklists[o.stage].filter(i=>i.gating&&i.status!=='Completed'&&i.status!=='Not required').length;

  const updateOpp=(id:string,fn:(o:Opportunity)=>Opportunity)=>setOpps(prev=>prev.map(o=>o.id===id?fn(o):o));
  const stageMove=(o:Opportunity,dir:-1|1)=>{const idx=stages.indexOf(o.stage);const target=stages[Math.max(0,Math.min(stages.length-1,idx+dir))];if(dir===1&&pending(o)>0)return;updateOpp(o.id,x=>({...x,stage:target,probability:probs[target],daysInStage:0}));log(dir===1?'stage_advanced':'stage_moved_back',o,`${o.stage} -> ${target}`); setActive(active&&active.id===o.id?{...o,stage:target,probability:probs[target],daysInStage:0}:active);};

  return <div className='min-h-screen bg-white text-slate-800'>
    <header className='bg-blue-700 text-white p-3'>
      <div className='flex items-center gap-3 justify-between'><div className='font-semibold'>O2O Tracker (Opportunity to Order) ConveGenius</div><div>{new Date().toDateString()}</div><input className='rounded px-2 py-1 text-slate-800 w-64' placeholder='Search opportunities' value={query} onChange={e=>setQuery(e.target.value)}/><div>🔔</div><div>User: Demo</div><span className='bg-blue-900 px-2 py-1 rounded text-xs'>{role}</span><button className='bg-white text-blue-700 px-2 py-1 rounded text-sm'>Logout</button></div>
      <div className='mt-2 flex gap-2 items-center'><Nav t='Home' tab={tab} setTab={setTab}/><Nav t='Admin' tab={tab} setTab={setTab}/><Nav t='Audit Log' tab={tab} setTab={setTab}/><select className='ml-auto text-slate-800 rounded px-2 py-1' value={role} onChange={e=>setRole(e.target.value as Role)}>{roles.map(r=><option key={r}>{r}</option>)}</select></div>
    </header>

    {tab==='Home'&&<main className='p-4 space-y-4'>
      <section className='grid md:grid-cols-4 gap-3'>{[['Total Pipeline',kpi.total.toFixed(1)+' Cr'],['Weighted Pipeline',kpi.weighted.toFixed(1)+' Cr'],['High Confidence',kpi.high],['Orders Won',kpi.won]].map(([k,v])=><div key={String(k)} className='border rounded p-3 bg-slate-50'><p className='text-sm text-slate-500'>{k}</p><p className='text-2xl font-semibold'>{v}</p></div>)}</section>
      <section className='flex flex-wrap gap-2 items-center border rounded p-3 bg-slate-50'>{['type','product','geo','stage','status','salesperson'].map((k)=><select key={k} className='border rounded px-2 py-1 text-sm' value={(filters as any)[k]} onChange={e=>setFilters(f=>({...f,[k]:e.target.value}))}><option>All</option>{k==='type'&&['B2G','B2B'].map(v=><option key={v}>{v}</option>)}{k==='stage'&&stages.map(v=><option key={v}>{v}</option>)}{k==='status'&&['Active','Lost','No-Bid','Dropped','Archived','On Hold','No-Go'].map(v=><option key={v}>{v}</option>)}{k==='salesperson'&&Array.from(new Set(opps.map(o=>o.owner))).map(v=><option key={v}>{v}</option>)}{k==='geo'&&Array.from(new Set(opps.flatMap(o=>o.geos))).map(v=><option key={v}>{v}</option>)}{k==='product'&&Array.from(new Set(opps.flatMap(o=>o.products))).map(v=><option key={v}>{v}</option>)}</select>)}<label className='text-sm'><input type='checkbox' checked={showArchived} onChange={e=>setShowArchived(e.target.checked)}/> Show archived</label><button disabled={!can('add')} title={can('add')?'':'Not permitted for selected role.'} onClick={()=>setShowAdd(true)} className='ml-auto bg-blue-700 text-white px-3 py-1 rounded disabled:bg-slate-300'>+ Add Opportunity</button></section>
      <section className='overflow-auto'><div className='grid grid-cols-8 gap-2 min-w-[1700px]'>{stages.map(s=>{const list=view.filter(o=>o.stage===s);const total=list.reduce((a,b)=>a+b.valueCr,0);return <div key={s} className='border rounded bg-slate-50 p-2'><div className='mb-2 text-xs'><div className='font-semibold'>{s}</div><div>Weight {probs[s]}% · Count {list.length} · ₹{total.toFixed(1)} Cr</div></div><div className='space-y-2'>{list.map(o=><button key={o.id} onClick={()=>{setActive(o);setDtab('Checklist')}} className='w-full text-left border rounded bg-white p-2 text-xs'><div className='font-semibold'>{o.name}</div><div className='flex gap-1 my-1'><Pill t={o.status}/><span className='px-1 rounded bg-slate-100'>{o.type}</span><span className='px-1 rounded bg-slate-100'>{o.motion}</span></div><div>{o.department} / {o.customer}</div><div>{o.products.map(p=><span key={p} className='inline-block bg-blue-50 mr-1 px-1 rounded'>{p}</span>)}</div><div>₹{o.valueCr} Cr · Checklist {o.checklists[o.stage].filter(i=>i.status==='Completed').length}/{o.checklists[o.stage].length}</div><div>Evidence {Math.round((o.checklists[o.stage].filter(i=>!i.evidenceRequired||i.files>0).length/o.checklists[o.stage].length)*100)}% · Comments {o.comments.length} · Files {o.files.length}</div><div>Days {o.daysInStage} · Owner {o.owner}</div><div>RC {o.rcPod} · Sponsor {o.podSponsor}</div><div>Blocker: {o.currentBlocker}</div><div>Next: {o.nextAction}</div></button>)}</div></div>})}</div></section>
    </main>}

    {tab==='Admin'&&<main className='p-4 space-y-4'>{can('admin')?<><h2 className='font-semibold text-lg'>Admin</h2><div className='grid md:grid-cols-2 gap-4'><Table title='Users' headers={['Name','Email','Role','Reports To','Status','Last Login','Actions']} rows={[[`Aditi`,`aditi@cg.com`,`BD`,`Rishabh`,`Active`,`2026-05-20`,`Edit`],[`Somesh`,`somesh@cg.com`,`CFO / Somesh`,`Prateek`,`Active`,`2026-05-20`,`Edit`]]}/><Table title='Roles' headers={['Role']} rows={roles.map(r=>[r])}/></div><Table title='Checklist Templates' headers={['Stage','Item','Role Visibility','Evidence required','Is gating item','Source Rule']} rows={stages.flatMap(s=>templates[s].slice(0,2).map(i=>[s,i,'BD, GI, Admin','Yes','Yes','PRD Rule']))}/><Table title='Dropdowns' headers={['Category','Values']} rows={[['Departments / Customers','Education Dept, CSR, FLN Mission'],['Products','LMS, Assessment, STEM Kits'],['Geography','UP, MH, MP, BR, RJ'],['Statuses','Active, Lost, No-Bid, Dropped, Archived'],['Loss reasons','Budget cut, Competitor win, Compliance gap']]}/></>:<div className='text-sm text-slate-500'>Not permitted for selected role.</div>}</main>}

    {tab==='Audit Log'&&<main className='p-4'><Table title='Audit Log' headers={['Time','User','Event','Opportunity','Details']} rows={audit.map(a=>[a.time,a.user,a.event,a.opportunity,a.details])}/></main>}

    {showAdd&&<AddModal onClose={()=>setShowAdd(false)} disabled={!can('add')} onAdd={(x)=>{const n:Opportunity={id:`OP-${Math.floor(Math.random()*900+100)}`,name:x.name,department:x.department,customer:x.customer,type:x.type,motion:x.motion,products:x.products,geos:x.geos,valueCr:x.valueCr,expectedClose:x.expectedClose,owner:x.owner,giOwner:x.giOwner,rcPod:x.rcPod,podSponsor:x.podSponsor,stage:'Opportunity Registration',status:'Active',probability:probs['Opportunity Registration'],daysInStage:0,currentBlocker:'',nextAction:'',checklists:mkChecklist(),comments:[],files:[],cfoSigned:false,bidSubmitted:false,awardUploaded:false,mouUploaded:false};setOpps(p=>[n,...p]);log('opportunity_created',n,'Created from Add Opportunity');setShowAdd(false);setActive(n);}}/>}

    {active&&<Detail opp={active} setOpp={(fn)=>{updateOpp(active.id,o=>{const u=fn(o);setActive(u);return u;});}} close={()=>setActive(null)} dtab={dtab} setDtab={setDtab} pending={pending(active)} can={can} onLog={log} onMove={(d)=>stageMove(active,d)} />}
  </div>;
}

function Nav({t,tab,setTab}:{t:TopTab;tab:TopTab;setTab:(t:TopTab)=>void}){return <button onClick={()=>setTab(t)} className={`px-3 py-1 rounded ${tab===t?'bg-white text-blue-700':'bg-blue-600'}`}>{t}</button>}
function Pill({t}:{t:string}){return <span className='px-1 rounded bg-slate-200'>{t}</span>}
function Table({title,headers,rows}:{title:string;headers:string[];rows:(string|number)[][]}){return <div className='border rounded p-2'><h3 className='font-semibold mb-2'>{title}</h3><table className='w-full text-xs'><thead><tr>{headers.map(h=><th key={h} className='text-left border-b p-1'>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j} className='p-1 border-b'>{c}</td>)}</tr>)}</tbody></table></div>}

function AddModal({onClose,onAdd,disabled}:{onClose:()=>void;onAdd:(p:any)=>void;disabled:boolean}){const [f,setF]=useState({name:'',department:'Education Dept',customer:'',motion:'Hunting',type:'B2G',geos:['UP'],products:['LMS'],valueCr:10,expectedClose:'2026-06-30',owner:'Aditi (BD)',giOwner:'Vikram (GI)',rcPod:'RC North',podSponsor:'N. Kapoor'} as any);const tog=(k:'geos'|'products',v:string)=>setF((x:any)=>({...x,[k]:x[k].includes(v)?x[k].filter((i:string)=>i!==v):[...x[k],v]}));return <div className='fixed inset-0 bg-black/40 grid place-items-center p-4'><div className='bg-white rounded p-4 w-full max-w-2xl'><h3 className='font-semibold mb-2'>Add Opportunity</h3><div className='grid md:grid-cols-2 gap-2 text-sm'><input className='border rounded p-1' placeholder='Opportunity name' value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><input className='border rounded p-1' placeholder='Department / customer' value={f.customer} onChange={e=>setF({...f,customer:e.target.value})}/><select className='border rounded p-1' value={f.motion} onChange={e=>setF({...f,motion:e.target.value})}><option>Farming</option><option>Hunting</option></select><select className='border rounded p-1' value={f.type} onChange={e=>setF({...f,type:e.target.value})}><option>B2G</option><option>B2B</option></select><input className='border rounded p-1' type='number' value={f.valueCr} onChange={e=>setF({...f,valueCr:Number(e.target.value)})}/><input className='border rounded p-1' type='date' value={f.expectedClose} onChange={e=>setF({...f,expectedClose:e.target.value})}/><input className='border rounded p-1' value={f.owner} onChange={e=>setF({...f,owner:e.target.value})}/><input className='border rounded p-1' value={f.giOwner} onChange={e=>setF({...f,giOwner:e.target.value})}/><input className='border rounded p-1' value={f.rcPod} onChange={e=>setF({...f,rcPod:e.target.value})}/><input className='border rounded p-1' value={f.podSponsor} onChange={e=>setF({...f,podSponsor:e.target.value})}/><div><div>Geography</div>{['UP','MH','MP','BR','RJ'].map(g=><label key={g} className='mr-2'><input type='checkbox' checked={f.geos.includes(g)} onChange={()=>tog('geos',g)}/> {g}</label>)}</div><div><div>Products</div>{['LMS','Assessment','STEM Kits','Teacher App'].map(g=><label key={g} className='mr-2'><input type='checkbox' checked={f.products.includes(g)} onChange={()=>tog('products',g)}/> {g}</label>)}</div></div><div className='mt-3 flex justify-end gap-2'><button onClick={onClose} className='border rounded px-3 py-1'>Cancel</button><button disabled={disabled||!f.name||!f.customer} title={disabled?'Not permitted for selected role.':''} onClick={()=>onAdd(f)} className='bg-blue-700 text-white rounded px-3 py-1 disabled:bg-slate-300'>Add Opportunity</button></div></div></div>}

function Detail({opp,setOpp,close,dtab,setDtab,pending,can,onLog,onMove}:{opp:Opportunity;setOpp:(fn:(o:Opportunity)=>Opportunity)=>void;close:()=>void;dtab:string;setDtab:(s:string)=>void;pending:number;can:(p:any)=>boolean;onLog:(e:string,o:any,d:string)=>void;onMove:(d:-1|1)=>void}){
  const t=['Checklist','Comments','Files','PAB','Financials / CM2','RFP & Bid','MOU','O2C Handover','Activity / Audit'];
  return <div className='fixed inset-0 bg-black/40 p-4 overflow-auto'><div className='bg-white rounded p-4 max-w-6xl mx-auto'>
    <div className='flex items-center gap-2 flex-wrap'><h3 className='font-semibold text-lg'>{opp.name}</h3><Pill t={opp.stage}/><Pill t={opp.status}/><Pill t={`Weight ${opp.probability}%`}/><Pill t={opp.type}/><Pill t={opp.motion}/><button className='border px-2 rounded text-sm'>Edit</button><button onClick={close} className='ml-auto border px-2 rounded'>Close</button></div>
    <div className='text-sm mt-2 grid md:grid-cols-4 gap-2'><div>{opp.customer} / {opp.department}</div><div>{opp.geos.join(', ')}</div><div>₹{opp.valueCr} Cr · {opp.expectedClose}</div><div>{opp.products.join(', ')} · {opp.owner}</div><div>RC {opp.rcPod}</div><div>Sponsor {opp.podSponsor}</div><div>Days in stage {opp.daysInStage}</div></div>
    <div className={`mt-2 p-2 rounded text-sm ${pending===0?'bg-emerald-100 text-emerald-800':'bg-amber-100 text-amber-900'}`}>{pending===0?'All required items addressed — ready to advance.':`${pending} required item(s) pending before this opportunity can advance.`} | Evidence health {Math.round((opp.checklists[opp.stage].filter(i=>!i.evidenceRequired||i.files>0).length/opp.checklists[opp.stage].length)*100)}% | Pending blockers {pending} | Required action: {opp.nextAction||'Update checklist'}</div>
    <div className='mt-2 flex flex-wrap gap-1'>{t.map(x=><button key={x} onClick={()=>setDtab(x)} className={`px-2 py-1 rounded text-xs ${dtab===x?'bg-blue-700 text-white':'bg-slate-100'}`}>{x}</button>)}</div>

    {dtab==='Checklist'&&<div className='mt-3 space-y-2'>{opp.checklists[opp.stage].map(it=><div key={it.id} className='border rounded p-2 text-sm'><div className='font-medium'>{it.title} {it.evidenceRequired&&<span className='text-xs bg-amber-100 px-1 rounded'>Evidence required</span>} {it.sourceRule&&<span className='text-xs bg-blue-100 px-1 rounded ml-1'>Source Rule</span>}</div><div className='grid md:grid-cols-4 gap-2 mt-1'><select className='border rounded p-1' value={it.status} onChange={e=>{setOpp(o=>({...o,checklists:{...o.checklists,[o.stage]:o.checklists[o.stage].map(c=>c.id===it.id?{...c,status:e.target.value as CStatus}:c)}})); onLog('checklist_updated',opp,`${it.title} -> ${e.target.value}`);}}><option>Not completed</option><option>Completed</option><option>Not required</option></select><textarea className='border rounded p-1' placeholder='Comment' value={it.note} onChange={e=>setOpp(o=>({...o,checklists:{...o.checklists,[o.stage]:o.checklists[o.stage].map(c=>c.id===it.id?{...c,note:e.target.value}:c)}}))}/><button className='border rounded px-2' onClick={()=>{setOpp(o=>({...o,checklists:{...o.checklists,[o.stage]:o.checklists[o.stage].map(c=>c.id===it.id?{...c,files:c.files+1}:c)},files:[{id:`f${Date.now()}`,name:`${it.title}.pdf`,type:'pdf',checklist:it.title,by:'User',date:now()},...o.files]}));onLog('file_uploaded',opp,`File attached to ${it.title}`);}}>Attach file</button></div></div>)}
      <div className='flex flex-wrap gap-2'><button className='border rounded px-2 py-1' onClick={()=>onMove(-1)}>Move back</button><button disabled={pending>0} title={pending>0?'Required checklist items pending':''} className='border rounded px-2 py-1 disabled:bg-slate-200' onClick={()=>onMove(1)}>Advance</button><button className='border rounded px-2 py-1' onClick={()=>{setOpp(o=>({...o,status:'Lost'}));onLog('status_changed',opp,'Marked Lost')}}>Mark as Lost</button><button className='border rounded px-2 py-1' onClick={()=>onLog('status_changed',opp,'Transfer requested')}>Transfer</button><button className='border rounded px-2 py-1' onClick={()=>{setOpp(o=>({...o,status:'Archived'}));onLog('status_changed',opp,'Archived')}}>Archive</button><button className='border rounded px-2 py-1' onClick={()=>onLog('status_changed',opp,'Delete requested (placeholder)')}>Delete</button><button className='border rounded px-2 py-1' onClick={close}>Close</button></div>
    </div>}

    {dtab==='Comments'&&<Comments opp={opp} setOpp={setOpp} onLog={onLog}/>} {dtab==='Files'&&<Files opp={opp} setOpp={setOpp}/>} {dtab==='PAB'&&<Pab opp={opp} setOpp={setOpp} can={can} onLog={onLog}/>} {dtab==='Financials / CM2'&&<Financial opp={opp} setOpp={setOpp} can={can} onLog={onLog}/>} {dtab==='RFP & Bid'&&<Rfp opp={opp} setOpp={setOpp} can={can} onLog={onLog}/>} {dtab==='MOU'&&<Mou opp={opp} setOpp={setOpp} can={can} onLog={onLog}/>} {dtab==='Activity / Audit'&&<div className='mt-3 text-sm'>Activity recorded in global Audit Log tab.</div>} {dtab==='O2C Handover'&&<div className='mt-3 text-sm'>{opp.mouUploaded?'Ready for O2C transition':'Pending signed MOU upload.'}</div>}
  </div></div>
}

function Comments({opp,setOpp,onLog}:{opp:Opportunity;setOpp:any;onLog:any}){const [t,setT]=useState('');return <div className='mt-3 text-sm'><div className='space-y-1'>{opp.comments.map(c=><div key={c.id} className='border rounded p-2'><b>{c.author}</b> · {c.at}<div>{c.text}</div></div>)}</div><textarea className='border rounded p-2 w-full mt-2' placeholder='Add comment (@mention...)' value={t} onChange={e=>setT(e.target.value)}/><button className='mt-2 bg-blue-700 text-white rounded px-3 py-1' onClick={()=>{if(!t.trim())return;setOpp((o:Opportunity)=>({...o,comments:[{id:`c${Date.now()}`,author:'Current User',at:now(),text:t},...o.comments]}));onLog('comment_added',opp,'Comment added');setT('');}}>Add Comment</button></div>}
function Files({opp}:{opp:Opportunity;setOpp:any}){return <table className='w-full text-sm mt-3'><thead><tr><th>File name</th><th>File type</th><th>Linked checklist item</th><th>Uploaded by</th><th>Uploaded date</th><th>Delete</th></tr></thead><tbody>{opp.files.map(f=><tr key={f.id}><td>{f.name}</td><td>{f.type}</td><td>{f.checklist}</td><td>{f.by}</td><td>{f.date}</td><td>Delete</td></tr>)}</tbody></table>}
function Pab({opp,setOpp,can,onLog}:{opp:Opportunity;setOpp:any;can:any;onLog:any}){const [d,setD]=useState<'Go'|'Conditional Go'|'Hold'|'No-Go'>('Go');const [c,setC]=useState('');const [m,setM]=useState('');const ok=can('pab');return <div className='mt-3 text-sm space-y-2'><div>Conveners: Rishabh + Prateek | Mandatory: RC Pod, Pod Sponsor, Rishabh, Prateek</div><select className='border rounded p-1' value={d} onChange={e=>setD(e.target.value as any)}><option>Go</option><option>Conditional Go</option><option>Hold</option><option>No-Go</option></select><textarea className='border rounded p-1 w-full' placeholder='Conditions' value={c} onChange={e=>setC(e.target.value)}/><textarea className='border rounded p-1 w-full' placeholder='Minutes / rationale' value={m} onChange={e=>setM(e.target.value)}/><button disabled={!ok} title={ok?'':'Not permitted for selected role.'} className='border rounded px-2 py-1 disabled:bg-slate-200' onClick={()=>{setOpp((o:Opportunity)=>{let u={...o,pabDecision:d};if(d==='Go')u={...u,stage:'Financial Approval Gate',probability:45};if(d==='Hold')u={...u,status:'On Hold'};if(d==='No-Go')u={...u,status:'No-Go'};return u;});onLog('pab_decision_recorded',opp,`${d}; ${c}; ${m}`);}}>Record decision</button></div>}
function Financial({opp,setOpp,can,onLog}:{opp:Opportunity;setOpp:any;can:any;onLog:any}){const ok=can('cfo');return <div className='mt-3 text-sm space-y-1'><div>CM2 pricing sheet version: v2.4</div><div>CCOO pricing strategy reference: CCOO-PS-2026-04</div><div>Margin summary: 23.4%</div><div>Commercial risk: Moderate</div><div>Payment milestone draft: 30/40/30</div><div>CFO sign-off status: {opp.cfoSigned?'Recorded':'Pending'}</div><button disabled={!ok||opp.cfoSigned} title={ok?'':'Not permitted for selected role.'} className='border rounded px-2 py-1 disabled:bg-slate-200' onClick={()=>{setOpp((o:Opportunity)=>({...o,cfoSigned:true}));onLog('cfo_signoff_recorded',opp,'CFO sign-off recorded');}}>CFO sign-off</button></div>}
function Rfp({opp,setOpp,can,onLog}:{opp:Opportunity;setOpp:any;can:any;onLog:any}){const ok=can('tender');return <div className='mt-3 text-sm space-y-2'><div>RFP upload placeholder · Technical bid upload placeholder · Financial bid upload placeholder · EMD proof · Compliance checklist · Submission acknowledgement · Award communication upload</div><div className='flex gap-2 flex-wrap'><button disabled={!ok||!opp.cfoSigned} title={!opp.cfoSigned?'No proposal can move to bid submission without CFO sign-off.':ok?'':'Not permitted for selected role.'} className='border rounded px-2 py-1 disabled:bg-slate-200' onClick={()=>{setOpp((o:Opportunity)=>({...o,bidSubmitted:true}));onLog('bid_submitted',opp,'Bid submitted');}}>Mark Bid Submitted</button><button disabled={!ok} className='border rounded px-2 py-1 disabled:bg-slate-200' onClick={()=>{setOpp((o:Opportunity)=>({...o,awardUploaded:true}));onLog('award_communication_uploaded',opp,'Award communication uploaded');}}>Upload Award Communication</button><button disabled={!ok||!opp.awardUploaded} title={!opp.awardUploaded?'Won disabled until Award Communication exists':''} className='border rounded px-2 py-1 disabled:bg-slate-200' onClick={()=>{setOpp((o:Opportunity)=>({...o,status:'Active'}));onLog('status_changed',opp,'Marked Won')}}>Mark Won</button><button disabled={!ok} className='border rounded px-2 py-1 disabled:bg-slate-200' onClick={()=>{setOpp((o:Opportunity)=>({...o,status:'Lost'}));onLog('status_changed',opp,'Marked Lost from RFP tab')}}>Mark Lost</button><button disabled={!ok} className='border rounded px-2 py-1 disabled:bg-slate-200' onClick={()=>{setOpp((o:Opportunity)=>({...o,status:'No-Bid'}));onLog('status_changed',opp,'Marked No-Bid from RFP tab')}}>Mark No-Bid</button></div></div>}
function Mou({opp,setOpp,can,onLog}:{opp:Opportunity;setOpp:any;can:any;onLog:any}){const ok=can('mou');return <div className='mt-3 text-sm space-y-1'><div>MOU draft version: v1.3</div><div>Scope alignment confirmation ✓</div><div>Pricing alignment confirmation ✓</div><div>Payment milestone clarity ✓</div><div>Operational realism confirmation ✓</div><div>Prateek sign-off ✓ | Rishabh sign-off ✓</div><div>Signed MOU upload placeholder</div><button disabled={!ok||opp.mouUploaded} title={ok?'':'Not permitted for selected role.'} className='border rounded px-2 py-1 disabled:bg-slate-200' onClick={()=>{setOpp((o:Opportunity)=>({...o,mouUploaded:true,stage:'O2C Transition Ready',probability:100}));onLog('mou_uploaded',opp,'Ready for O2C transition');}}>Upload Signed MOU</button>{opp.mouUploaded&&<div className='text-emerald-700 font-medium'>Ready for O2C transition</div>}</div>}
