import { useMemo, useState } from 'react';

type Tab = 'Home' | 'Admin' | 'Audit Log';
type Role = 'Admin'|'BD'|'GI'|'RC Pod'|'Rishabh / CXO Lead'|'Prateek / CXO Lead'|'CFO / Somesh'|'Tender Team'|'Readonly';
type Stage = 'Opportunity Registration'|'Proposal Stage'|'Pre-Bid PAB'|'Financial Approval Gate'|'RFP & Bid Management'|'Post-Bid PAB'|'MOU Stage'|'O2C Transition Ready';
type Status = 'Active'|'Lost'|'No-Bid'|'Dropped'|'Archived'|'On Hold'|'No-Go';
type CStatus = 'Not completed'|'Completed'|'Not required';

type Item = { id:string; title:string; status:CStatus; note:string; files:number; evidence?:boolean; rule?:string };
type Comment = { id:string; author:string; ts:string; text:string };
type F = { id:string; name:string; type:string; linked:string; by:string; date:string };
type Opp = { id:string; name:string; customer:string; dept:string; type:'B2G'|'B2B'; motion:'Farming'|'Hunting'; products:string[]; geo:string[]; value:number; close:string; owner:string; rcPod:string; sponsor:string; stage:Stage; status:Status; prob:number; days:number; blocker:string; next:string; cl:Record<Stage,Item[]>; comments:Comment[]; files:F[]; cfo:boolean; award:boolean; mou:boolean };
type Audit = { id:string; time:string; user:string; event:string; opportunity:string; details:string };

const stages:Stage[]=['Opportunity Registration','Proposal Stage','Pre-Bid PAB','Financial Approval Gate','RFP & Bid Management','Post-Bid PAB','MOU Stage','O2C Transition Ready'];
const weights:Record<Stage,number>={'Opportunity Registration':10,'Proposal Stage':25,'Pre-Bid PAB':35,'Financial Approval Gate':45,'RFP & Bid Management':60,'Post-Bid PAB':75,'MOU Stage':90,'O2C Transition Ready':100};
const tmpl:Record<Stage,string[]>= {
'Opportunity Registration':['Customer signal captured','Budget signal captured','Stakeholder mapping completed','Competitor intelligence captured'],
'Proposal Stage':['Problem framing completed','Scope and timelines documented','CM2 pricing sheet prepared','Rollout assumptions documented','Success definition articulated','Platform dependencies identified','Risk assumptions uploaded','Stakeholder map uploaded'],
'Pre-Bid PAB':['Proposal submitted to CXO layer','Pre-Bid PAB scheduled','Platform feasibility validated','Delivery feasibility validated','Capacity read captured','CM2 aligned with CCOO-approved pricing strategy','PAB decision recorded'],
'Financial Approval Gate':['Margin validation completed','Commercial risk reviewed','Payment milestones reviewed','CM2 approved','Third-party delivery expenses approved','CFO sign-off recorded'],
'RFP & Bid Management':['RFP document uploaded','Technical bid uploaded','Financial bid uploaded','EMD / tender fee proof uploaded','Compliance checklist completed','Submission acknowledgement stored','Award communication uploaded, if won'],
'Post-Bid PAB':['Capacity readiness reviewed','Execution plan completed','Pod creation recommendation recorded','Hiring requests recorded','Risk register created','O2C readiness confirmed'],
'MOU Stage':['MOU draft uploaded','Scope alignment confirmed','Pricing alignment confirmed','Payment milestone clarity confirmed','Operational realism confirmed','Prateek sign-off recorded','Rishabh sign-off recorded','Signed MOU uploaded'],
'O2C Transition Ready':['Transition packet confirmed']
};
const ts=()=>new Date().toISOString().slice(0,16).replace('T',' ');
const mk=()=>Object.fromEntries(stages.map(s=>[s,tmpl[s].map((x,i)=>({id:`${s}-${i}`,title:x,status:i<2?'Completed':'Not completed',note:'',files:0,evidence:i%2===0,rule:i%3===0?'Source Rule':undefined}))])) as Record<Stage,Item[]>;
const seed:Opp[]=[
{id:'OP-1',name:'UP FLN Renewal',customer:'UP DoE',dept:'Education',type:'B2G',motion:'Hunting',products:['LMS','Assessment'],geo:['UP'],value:32,close:'2026-07-30',owner:'Aditi',rcPod:'RC North',sponsor:'N Kapoor',stage:'Opportunity Registration',status:'Active',prob:10,days:4,blocker:'Budget note pending',next:'Capture budget',cl:mk(),comments:[],files:[],cfo:false,award:false,mou:false},
{id:'OP-2',name:'CSR STEM Enablement',customer:'Apex',dept:'CSR',type:'B2B',motion:'Farming',products:['STEM Kits'],geo:['MH'],value:14,close:'2026-06-25',owner:'Rohan',rcPod:'RC West',sponsor:'P Bhat',stage:'Proposal Stage',status:'Active',prob:25,days:7,blocker:'Risk assumptions',next:'Upload risks',cl:mk(),comments:[],files:[],cfo:false,award:false,mou:false},
{id:'OP-3',name:'Tablet Upgrade',customer:'MP Education',dept:'School IT',type:'B2G',motion:'Hunting',products:['Device Mgmt'],geo:['MP'],value:48,close:'2026-08-15',owner:'Ishita',rcPod:'RC Central',sponsor:'R Jain',stage:'Pre-Bid PAB',status:'Active',prob:35,days:3,blocker:'PAB decision',next:'Record minutes',cl:mk(),comments:[],files:[],cfo:false,award:false,mou:false},
{id:'OP-4',name:'FLN Scale',customer:'Bihar Dept',dept:'Mission',type:'B2G',motion:'Farming',products:['Teacher App'],geo:['BR'],value:28,close:'2026-07-12',owner:'Karan',rcPod:'RC East',sponsor:'M Das',stage:'Financial Approval Gate',status:'Active',prob:45,days:6,blocker:'CFO signoff',next:'Get CFO',cl:mk(),comments:[],files:[],cfo:false,award:false,mou:false},
{id:'OP-5',name:'Exam Prep Stack',customer:'Rajasthan Mission',dept:'Skill',type:'B2G',motion:'Hunting',products:['Exam Platform'],geo:['RJ'],value:19,close:'2026-06-18',owner:'Pooja',rcPod:'RC North',sponsor:'A Sen',stage:'RFP & Bid Management',status:'Active',prob:60,days:9,blocker:'EMD proof',next:'Upload EMD',cl:mk(),comments:[],files:[],cfo:true,award:false,mou:false},
{id:'OP-6',name:'Smart Lab Continuation',customer:'Odisha DoE',dept:'Education',type:'B2G',motion:'Farming',products:['LMS'],geo:['OD'],value:24,close:'2026-05-28',owner:'Tanuj',rcPod:'RC East',sponsor:'R Dey',stage:'Post-Bid PAB',status:'Active',prob:75,days:5,blocker:'Risk register',next:'Create risk register',cl:mk(),comments:[],files:[],cfo:true,award:true,mou:false},
{id:'OP-7',name:'Outcomes Partnership',customer:'Punjab Mission',dept:'Mission',type:'B2G',motion:'Hunting',products:['M&E'],geo:['PB'],value:21,close:'2026-06-10',owner:'Reva',rcPod:'RC North',sponsor:'S Talwar',stage:'MOU Stage',status:'Active',prob:90,days:7,blocker:'Signed MOU',next:'Upload signed MOU',cl:mk(),comments:[],files:[],cfo:true,award:true,mou:false},
{id:'OP-8',name:'Classroom Renewal',customer:'Delhi DoE',dept:'State Edu',type:'B2G',motion:'Farming',products:['LMS'],geo:['DL'],value:16,close:'2026-05-25',owner:'Nitin',rcPod:'RC Metro',sponsor:'V Shah',stage:'O2C Transition Ready',status:'Active',prob:100,days:2,blocker:'None',next:'Handover',cl:mk(),comments:[],files:[],cfo:true,award:true,mou:true}
];

export default function App(){
  const [tab,setTab]=useState<Tab>('Home'); const [role,setRole]=useState<Role>('BD'); const [q,setQ]=useState('');
  const [f,setF]=useState({type:'All',product:'All',geo:'All',stage:'All',status:'All',sales:'All',arch:false});
  const [opps,setOpps]=useState(seed); const [audit,setAudit]=useState<Audit[]>([]); const [showAdd,setShowAdd]=useState(false); const [active,setActive]=useState<Opp|null>(null); const [dt,setDt]=useState('Checklist');
  const can=(p:'add'|'admin'|'pab'|'cfo'|'tender'|'mou')=>({add:['BD'],admin:['Admin'],pab:['Rishabh / CXO Lead','Prateek / CXO Lead'],cfo:['CFO / Somesh'],tender:['Tender Team'],mou:['GI']}[p] as Role[]).includes(role);
  const log=(event:string,o:string,d:string)=>setAudit(a=>[{id:`a${Date.now()}`,time:ts(),user:role,event,opportunity:o,details:d},...a]);
  const list=opps.filter(o=>(f.arch||o.status!=='Archived')&&`${o.name} ${o.customer}`.toLowerCase().includes(q.toLowerCase())&&(f.type==='All'||o.type===f.type)&&(f.product==='All'||o.products.includes(f.product))&&(f.geo==='All'||o.geo.includes(f.geo))&&(f.stage==='All'||o.stage===f.stage)&&(f.status==='All'||o.status===f.status)&&(f.sales==='All'||o.owner===f.sales));
  const k=useMemo(()=>({tp:list.reduce((a,b)=>a+b.value,0),wp:list.reduce((a,b)=>a+b.value*b.prob/100,0),hc:list.filter(x=>x.prob>=75).length,ow:list.filter(x=>x.stage==='O2C Transition Ready').length}),[list]);
  const pend=(o:Opp)=>o.cl[o.stage].filter(i=>i.status==='Not completed').length;

  return <div className='min-h-screen bg-white text-slate-800'>
    <header className='bg-blue-700 text-white p-3'><div className='flex items-center gap-3'><b>O2O Tracker (Opportunity to Order) ConveGenius</b><span>{new Date().toDateString()}</span><input className='ml-2 rounded px-2 py-1 text-slate-700 w-64' placeholder='Search' value={q} onChange={e=>setQ(e.target.value)}/><span>🔔</span><span>User: Demo</span><span className='bg-blue-900 rounded px-2 py-1 text-xs'>{role}</span><button className='bg-white text-blue-700 px-2 py-1 rounded'>Logout</button><select className='ml-auto text-slate-700 rounded px-2 py-1' value={role} onChange={e=>setRole(e.target.value as Role)}>{['Admin','BD','GI','RC Pod','Rishabh / CXO Lead','Prateek / CXO Lead','CFO / Somesh','Tender Team','Readonly'].map(r=><option key={r}>{r}</option>)}</select></div>
    <div className='mt-2 flex gap-2'>{(['Home','Admin','Audit Log'] as Tab[]).map(t=><button key={t} onClick={()=>setTab(t)} className={`px-3 py-1 rounded ${tab===t?'bg-white text-blue-700':'bg-blue-600'}`}>{t}</button>)}</div></header>

    {tab==='Home'&&<main className='p-4 space-y-3'>
      <section className='grid md:grid-cols-4 gap-3'>{[['Total Pipeline',k.tp.toFixed(1)+' Cr'],['Weighted Pipeline',k.wp.toFixed(1)+' Cr'],['High Confidence',k.hc],['Orders Won',k.ow]].map(([a,b])=><div key={String(a)} className='border rounded bg-slate-50 p-3'><div className='text-sm text-slate-500'>{a}</div><div className='text-2xl font-semibold'>{b}</div></div>)}</section>
      <section className='flex flex-wrap gap-2 border rounded p-3 bg-slate-50'>{[['type',['All','B2G','B2B']],['product',['All',...Array.from(new Set(opps.flatMap(o=>o.products)))]],['geo',['All',...Array.from(new Set(opps.flatMap(o=>o.geo)))]],['stage',['All',...stages]],['status',['All','Active','Lost','No-Bid','Dropped','Archived','On Hold','No-Go']],['sales',['All',...Array.from(new Set(opps.map(o=>o.owner)))]]] as const).map(([key,vals])=><select key={key} value={(f as any)[key]} onChange={e=>setF(x=>({...x,[key]:e.target.value}))} className='border rounded px-2 py-1 text-sm'>{vals.map(v=><option key={v}>{v}</option>)}</select>)}<label><input type='checkbox' checked={f.arch} onChange={e=>setF(x=>({...x,arch:e.target.checked}))}/> Show archived</label><button disabled={!can('add')} title={can('add')?'':'Not permitted for selected role.'} onClick={()=>setShowAdd(true)} className='ml-auto bg-blue-700 text-white rounded px-3 py-1 disabled:bg-slate-300'>+ Add Opportunity</button></section>
      <section className='overflow-auto'><div className='grid grid-cols-8 gap-2 min-w-[1700px]'>{stages.map(s=>{const col=list.filter(o=>o.stage===s);const tot=col.reduce((a,b)=>a+b.value,0);return <div key={s} className='border rounded bg-slate-50 p-2'><div className='text-xs mb-2'><div className='font-semibold'>{s}</div><div>Weight {weights[s]}% · Count {col.length} · ₹{tot.toFixed(1)} Cr</div></div><div className='space-y-2'>{col.map(o=><button key={o.id} onClick={()=>{setActive(o);setDt('Checklist')}} className='w-full text-left border rounded bg-white p-2 text-xs'><div className='font-semibold'>{o.name}</div><div>{o.status} · {o.type} · {o.motion}</div><div>{o.dept} / {o.customer}</div><div>{o.products.join(', ')}</div><div>₹{o.value} Cr · Checklist {o.cl[o.stage].filter(i=>i.status==='Completed').length}/{o.cl[o.stage].length}</div><div>Evidence {Math.round((o.cl[o.stage].filter(i=>!i.evidence||i.files>0).length/o.cl[o.stage].length)*100)}% · Comments {o.comments.length} · Files {o.files.length}</div><div>Days {o.days} · Owner {o.owner}</div><div>RC {o.rcPod} · Sponsor {o.sponsor}</div><div>Blocker: {o.blocker}</div><div>Next: {o.next}</div></button>)}</div></div>})}</div></section>
    </main>}

    {tab==='Admin'&&<main className='p-4'>{can('admin')?<div className='space-y-3'><h2 className='font-semibold'>Admin</h2><div className='flex gap-2 text-sm'><span className='bg-slate-900 text-white rounded px-2 py-1'>Users</span><span className='bg-slate-200 rounded px-2 py-1'>Roles</span><span className='bg-slate-200 rounded px-2 py-1'>Checklist Templates</span><span className='bg-slate-200 rounded px-2 py-1'>Dropdowns</span></div></div>:<div>Not permitted for selected role.</div>}</main>}
    {tab==='Audit Log'&&<main className='p-4'><table className='w-full text-sm'><thead><tr><th>Time</th><th>User</th><th>Event</th><th>Opportunity</th><th>Details</th></tr></thead><tbody>{audit.map(a=><tr key={a.id}><td>{a.time}</td><td>{a.user}</td><td>{a.event}</td><td>{a.opportunity}</td><td>{a.details}</td></tr>)}</tbody></table></main>}

    {showAdd&&<AddModal onClose={()=>setShowAdd(false)} onAdd={(x:any)=>{const n:Opp={id:`OP-${Math.floor(Math.random()*900+100)}`,name:x.name,customer:x.customer,dept:x.dept,type:x.type,motion:x.motion,products:x.products,geo:x.geo,value:x.value,close:x.close,owner:x.owner,rcPod:x.rcPod,sponsor:x.sponsor,stage:'Opportunity Registration',status:'Active',prob:10,days:0,blocker:'',next:'',cl:mk(),comments:[],files:[],cfo:false,award:false,mou:false};setOpps(p=>[n,...p]);log('opportunity_created',n.name,'Created from add modal');setShowAdd(false);setActive(n);}}/>}
    {active&&<Detail o={active} setO={(fn:any)=>setOpps(p=>p.map(x=>x.id===active.id?fn(x):x))} close={()=>setActive(null)} dt={dt} setDt={setDt} can={can} log={log} pending={pend(active)} />}
  </div>;
}

function AddModal({onClose,onAdd}:{onClose:()=>void;onAdd:(x:any)=>void}){const [f,setF]=useState({name:'',customer:'',dept:'Education',motion:'Hunting',type:'B2G',geo:['UP'],products:['LMS'],value:10,close:'2026-06-30',owner:'Aditi',giOwner:'Vikram',rcPod:'RC North',sponsor:'N Kapoor'} as any);const tg=(k:'geo'|'products',v:string)=>setF((x:any)=>({...x,[k]:x[k].includes(v)?x[k].filter((i:string)=>i!==v):[...x[k],v]}));return <div className='fixed inset-0 bg-black/40 grid place-items-center p-4'><div className='bg-white rounded p-4 w-full max-w-2xl'><h3 className='font-semibold'>Add Opportunity</h3><div className='grid md:grid-cols-2 gap-2 mt-2'><input className='border rounded p-1' placeholder='Opportunity name' value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><input className='border rounded p-1' placeholder='Department / customer' value={f.customer} onChange={e=>setF({...f,customer:e.target.value})}/><select className='border rounded p-1' value={f.motion} onChange={e=>setF({...f,motion:e.target.value})}><option>Farming</option><option>Hunting</option></select><select className='border rounded p-1' value={f.type} onChange={e=>setF({...f,type:e.target.value})}><option>B2G</option><option>B2B</option></select><input className='border rounded p-1' type='number' value={f.value} onChange={e=>setF({...f,value:Number(e.target.value)})}/><input className='border rounded p-1' type='date' value={f.close} onChange={e=>setF({...f,close:e.target.value})}/><input className='border rounded p-1' value={f.owner} onChange={e=>setF({...f,owner:e.target.value})}/><input className='border rounded p-1' value={f.giOwner} onChange={e=>setF({...f,giOwner:e.target.value})}/><input className='border rounded p-1' value={f.rcPod} onChange={e=>setF({...f,rcPod:e.target.value})}/><input className='border rounded p-1' value={f.sponsor} onChange={e=>setF({...f,sponsor:e.target.value})}/><div>{['UP','MH','MP','BR','RJ'].map(g=><label key={g} className='mr-2'><input type='checkbox' checked={f.geo.includes(g)} onChange={()=>tg('geo',g)}/> {g}</label>)}</div><div>{['LMS','Assessment','STEM Kits','Teacher App'].map(g=><label key={g} className='mr-2'><input type='checkbox' checked={f.products.includes(g)} onChange={()=>tg('products',g)}/> {g}</label>)}</div></div><div className='mt-3 flex justify-end gap-2'><button className='border rounded px-3 py-1' onClick={onClose}>Cancel</button><button className='bg-blue-700 text-white rounded px-3 py-1' onClick={()=>onAdd(f)}>Add Opportunity</button></div></div></div>}

function Detail({o,setO,close,dt,setDt,can,log,pending}:{o:Opp;setO:any;close:()=>void;dt:string;setDt:(x:string)=>void;can:any;log:any;pending:number}){const tabs=['Checklist','Comments','Files','PAB','Financials / CM2','RFP & Bid','MOU','O2C Handover','Activity / Audit'];return <div className='fixed inset-0 bg-black/40 p-4 overflow-auto'><div className='bg-white rounded p-4 max-w-6xl mx-auto'><div className='flex items-center gap-2 flex-wrap'><h3 className='font-semibold text-lg'>{o.name}</h3><span>{o.stage}</span><span>{o.status}</span><span>{o.prob}%</span><span>{o.type}</span><span>{o.motion}</span><button className='border rounded px-2'>Edit</button><button className='ml-auto border rounded px-2' onClick={close}>Close</button></div><div className='text-sm grid md:grid-cols-4 gap-2 mt-2'><div>{o.customer} / {o.dept}</div><div>{o.geo.join(', ')}</div><div>₹{o.value} Cr · {o.close}</div><div>{o.products.join(', ')} · {o.owner}</div><div>RC {o.rcPod}</div><div>Sponsor {o.sponsor}</div><div>Days {o.days}</div></div><div className={`mt-2 p-2 rounded text-sm ${pending===0?'bg-emerald-100':'bg-amber-100'}`}>{pending===0?'All required items addressed — ready to advance.':`${pending} required item(s) pending before this opportunity can advance.`}</div><div className='mt-2 flex gap-1 flex-wrap'>{tabs.map(t=><button key={t} onClick={()=>setDt(t)} className={`px-2 py-1 rounded text-xs ${dt===t?'bg-blue-700 text-white':'bg-slate-100'}`}>{t}</button>)}</div>
  {dt==='Checklist'&&<div className='mt-2 space-y-2'>{o.cl[o.stage].map((i:Item)=><div key={i.id} className='border rounded p-2 text-sm'><div>{i.title} {i.evidence&&<span className='bg-amber-100 rounded px-1 text-xs'>Evidence required</span>} {i.rule&&<span className='bg-blue-100 rounded px-1 text-xs ml-1'>Source Rule</span>}</div><div className='grid md:grid-cols-4 gap-2 mt-1'><select className='border rounded p-1' value={i.status} onChange={e=>{setO((x:Opp)=>({...x,cl:{...x.cl,[x.stage]:x.cl[x.stage].map(c=>c.id===i.id?{...c,status:e.target.value as CStatus}:c)}}));log('checklist_updated',o.name,`${i.title} -> ${e.target.value}`)}}><option>Not completed</option><option>Completed</option><option>Not required</option></select><textarea className='border rounded p-1' value={i.note} onChange={e=>setO((x:Opp)=>({...x,cl:{...x.cl,[x.stage]:x.cl[x.stage].map(c=>c.id===i.id?{...c,note:e.target.value}:c)}}))}/><button className='border rounded px-2' onClick={()=>{setO((x:Opp)=>({...x,cl:{...x.cl,[x.stage]:x.cl[x.stage].map(c=>c.id===i.id?{...c,files:c.files+1}:c)},files:[{id:`f${Date.now()}`,name:`${i.title}.pdf`,type:'pdf',linked:i.title,by:'User',date:ts()},...x.files]}));log('file_uploaded',o.name,`Attached to ${i.title}`)}}>Attach file</button></div></div>)}<div className='flex gap-2 flex-wrap'><button className='border rounded px-2 py-1' onClick={()=>log('stage_moved_back',o.name,'Move back clicked')}>Move back</button><button disabled={pending>0} title={pending>0?'Required checklist items pending':''} className='border rounded px-2 py-1 disabled:bg-slate-200' onClick={()=>log('stage_advanced',o.name,'Advance clicked')}>Advance</button><button className='border rounded px-2 py-1' onClick={()=>log('status_changed',o.name,'Marked Lost')}>Mark as Lost</button><button className='border rounded px-2 py-1'>Transfer</button><button className='border rounded px-2 py-1' onClick={()=>log('status_changed',o.name,'Archived')}>Archive</button><button className='border rounded px-2 py-1'>Delete</button><button className='border rounded px-2 py-1' onClick={close}>Close</button></div></div>}
  {dt==='Comments'&&<Comments o={o} setO={setO} log={log}/>} {dt==='Files'&&<table className='w-full text-sm mt-2'><thead><tr><th>File name</th><th>File type</th><th>Linked checklist item</th><th>Uploaded by</th><th>Uploaded date</th><th>Delete</th></tr></thead><tbody>{o.files.map(f=><tr key={f.id}><td>{f.name}</td><td>{f.type}</td><td>{f.linked}</td><td>{f.by}</td><td>{f.date}</td><td>Delete</td></tr>)}</tbody></table>}
  {dt==='PAB'&&<div className='mt-2 text-sm'><div>Conveners: Rishabh + Prateek | Mandatory participants: RC Pod, Pod Sponsor, Rishabh, Prateek</div><button disabled={!can('pab')} title={can('pab')?'':'Not permitted for selected role.'} className='border rounded px-2 py-1 mt-2 disabled:bg-slate-200' onClick={()=>log('pab_decision_recorded',o.name,'Decision recorded')}>Record decision</button></div>}
  {dt==='Financials / CM2'&&<div className='mt-2 text-sm'><div>CFO sign-off status: {o.cfo?'Recorded':'Pending'}</div><button disabled={!can('cfo')} title={can('cfo')?'':'Not permitted for selected role.'} className='border rounded px-2 py-1 mt-2 disabled:bg-slate-200' onClick={()=>log('cfo_signoff_recorded',o.name,'CFO sign-off recorded')}>CFO sign-off</button></div>}
  {dt==='RFP & Bid'&&<div className='mt-2 text-sm'><button disabled={!can('tender')} title={can('tender')?'':'Not permitted for selected role.'} className='border rounded px-2 py-1 disabled:bg-slate-200 mr-2' onClick={()=>log('bid_submitted',o.name,'Bid submitted')}>Mark Bid Submitted</button><button className='border rounded px-2 py-1 mr-2' onClick={()=>log('award_communication_uploaded',o.name,'Award uploaded')}>Upload Award Communication</button><button className='border rounded px-2 py-1 mr-2' onClick={()=>log('status_changed',o.name,'Marked Lost')}>Mark Lost</button><button className='border rounded px-2 py-1' onClick={()=>log('status_changed',o.name,'Marked No-Bid')}>Mark No-Bid</button></div>}
  {dt==='MOU'&&<div className='mt-2 text-sm'><button disabled={!can('mou')} title={can('mou')?'':'Not permitted for selected role.'} className='border rounded px-2 py-1 disabled:bg-slate-200' onClick={()=>log('mou_uploaded',o.name,'Ready for O2C transition')}>Upload Signed MOU</button></div>}
</div></div>}
}

function Comments({o,setO,log}:{o:Opp;setO:any;log:any}){const [t,setT]=useState('');return <div className='mt-2'><div className='space-y-1'>{o.comments.map(c=><div key={c.id} className='border rounded p-2 text-sm'><b>{c.author}</b> · {c.ts}<div>{c.text}</div></div>)}</div><textarea className='border rounded p-2 w-full mt-2' placeholder='Add comment (@mention...)' value={t} onChange={e=>setT(e.target.value)}/><button className='bg-blue-700 text-white rounded px-3 py-1 mt-2' onClick={()=>{if(!t.trim())return;setO((x:Opp)=>({...x,comments:[{id:`c${Date.now()}`,author:'Current User',ts:ts(),text:t},...x.comments]}));log('comment_added',o.name,'Comment added');setT('')}}>Add Comment</button></div>}
